### ISSUE TITLE
compiling error in linux

### ISSUE THREAD

**Issue by axelpersevalle** [MorsGames/sm64plus#11]
Hello,
I was compiling on linux and I got an error and the method is not tested so I tired
I will put the pictures of the error
![Capture d’écran du 2021-04-13 23-46-03](https://user-images.githubusercontent.com/78932119/114625419-838b7a80-9cb2-11eb-8d80-3f920cd10b91.png)
![Capture d’écran du 2021-04-13 23-46-24](https://user-images.githubusercontent.com/78932119/114625421-84241100-9cb2-11eb-889d-0319937d0dda.png)

I tried it in Ubuntu 20.04 and 20.10 and ArchLinux
I hope it will help for others and you

my best regards, bye

**Comment by MorsGames** [comment]
Will be fixed in the next release.
![image](https://user-images.githubusercontent.com/16962745/115136172-b1f8b500-a026-11eb-98d7-487c282c26eb.png)

**Comment by MorsGames** [comment]
Forgot to mention earlier but it should be already fixed in the dev branch now
