### ISSUE TITLE
automatic setup error 

### ISSUE THREAD

**Issue by RGG200** [MorsGames/sm64plus#13]
hello so i started the setup and after a while i got an error i restarted and then i got the same error:
here is the error:
avertissement : git-2.30.1-1 est à jour -- ignoré
avertissement : make-4.3-1 est à jour -- ignoré
avertissement : python-3.8.7-1 est à jour -- ignoré
avertissement : mingw-w64-x86_64-gcc-10.2.0-6 est à jour -- ignoré
avertissement : mingw-w64-x86_64-SDL2-2.0.14-2 est à jour -- ignoré
avertissement : mingw-w64-x86_64-glew-2.2.0-2 est à jour -- ignoré
 il n’y a rien à faire
The sm64plus folder already exists. Skipping cloning the repository.
extracting actors/amp/amp_body.rgba16.png
Error writing to "actors/amp/amp_body.rgba16.png"
Traceback (most recent call last):
  File "./extract_assets.py", line 292, in <module>
    main()
  File "./extract_assets.py", line 248, in main
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./tools/n64graphics', '-e', '/tmp/assetl7wy103_', '-g', 'actors/amp/amp_body.rgba16.png', '-f', 'rgba16', '-w', '32', '-h', '32']' returned non-zero exit status 1.
Makefile:143: *** Failed to extract assets. Arrêt.

how can i fix it?

**Comment by RGG200** [comment]
I am on version 1.1.2.0
I think the error come from here but i don't know how to fix it

**Comment by RGG200** [comment]
II tryed to change rom but didn't worl

**Comment by MorsGames** [comment]
Did you read the FAQ?

**Comment by MorsGames** [comment]
I'll be closing this since issues like this for building are extremely common, and often not directly related to this project in particular. Most of the time they can be fixed easily by simply reinstalling msys2 and/or disabling your antivirus.

**Comment by MorsGames** [comment]
Oops, accidental wrong label.
