### ISSUE TITLE
Textures are missing. 

### ISSUE THREAD

**Issue by bigBingus123** [MorsGames/sm64plus#16]
I am new to downloading games like this, so I am too sure what’s happening. Texters are missing but the game works fine I do not know if it is the Rom that I downloaded or something else.
![Screenshot (28)](https://user-images.githubusercontent.com/82684696/115094540-8caf5e00-9ee3-11eb-857e-8bb9c581b197.png)
![Screenshot (29)](https://user-images.githubusercontent.com/82684696/115094549-920ca880-9ee3-11eb-8b62-322eb4b1af4e.png)
![Screenshot (30)](https://user-images.githubusercontent.com/82684696/115094556-95a02f80-9ee3-11eb-9488-167d90a33158.png)

**Comment by MorsGames** [comment]
The FAQ addresses this.

**Comment by cgaldieri** [comment]
Im having a bigger version of this problem: https://github.com/MorsGames/sm64plus/issues/22

**Comment by MorsGames** [comment]
The latest version of the launcher should be fixing this issue automatically now.
