### ISSUE TITLE
Invisible rolling balls in Bomb Omb Battlefield

### ISSUE THREAD

**Issue by fluffybillygoat** [MorsGames/sm64plus#17]
They cause damage and I can hear them but I can't see.

**Comment by MorsGames** [comment]
Try deleting the "C:\Users\YourUsername\AppData\Local\SM64Plus\gfx" folder, not sure what the issue could be if that doesn't fix it though.

**Comment by fluffybillygoat** [comment]
> 
> 
> Try deleting the "C:\Users\YourUsername\AppData\Local\SM64Plus\gfx" folder, not sure what the issue could be if that doesn't fix it though.

No dice, I've noticed something this time though. The balls rolling back and forth at the bottom of the mountain are there, just not the ones rolling from the little caves.

**Comment by MorsGames** [comment]
Strange, you might want to recompile then, it's not an issue I've heard before.

**Comment by fluffybillygoat** [comment]
> 
> 
> Strange, you might want to recompile then, it's not an issue I've heard before.

I did the "pull and rebuild" option in the launcher if that's what you meant? Still the same. Could it be something wrong with the original SM64 game files that i'm using?

**Comment by MorsGames** [comment]
It can't be the game files. I'm not sure what it is then, I can't seem to replicate it myself, unfortunately. Could be a one-off occurrence. You can just try going through the building process all over again I guess.

I'll close this issue for now but if I hear more people have the same issue I will reopen it.

**Comment by shyguy85** [comment]
i  have this issue also
