### ISSUE TITLE
When nintendo comes... 

### ISSUE THREAD

**Issue by d0x360** [MorsGames/sm64plus#18]
And inevitably shuts this down despite not providing a rom... The launcher won't be able to download what it needs.

There should be a standalone version that can be downloaded that doesn't require anything but the launcher and a self provided rom.

**Comment by MorsGames** [comment]
I don't know why you say "inevitably" when every other fork of the port has been up for ages. Heck, they even took down the binaries and left the repositories alone. There's also this [Twitter](https://twitter.com/OfficialMFGG/status/1121019925521489920) thread to consider.

And if the game gets taken down by some chance I'm sure people will find a way to archive the game regardless.

I'll be closing any issues made about this in the future, this might seem weird to some but [I have my reasons](https://twitter.com/MorsGames/status/1384060107596599300).

**Comment by MorsGames** [comment]
Oops, accidental wrong label.
