### ISSUE TITLE
fullscreen monitor selection

### ISSUE THREAD

**Issue by pietergmail** [MorsGames/sm64plus#19]
When the game goes fullscreen it will always do so on the primary monitor. No setting to choose on which monitor to go fullscreen.

**Comment by MorsGames** [comment]
That's a good idea for a setting, I'll look into it.

**Comment by pietergmail** [comment]
Thank you for reviewing my suggestion. I also found a workaround by running the game in windowed and using borderless gaming to make it go fullscreen. But an ingame selection would be awesome.

**Comment by MorsGames** [comment]
It's added to the game now!
