### ISSUE TITLE
Wrong git URL on Readme

### ISSUE THREAD

**Issue by impeeza** [MorsGames/sm64plus#2]
Hi the Readme.MD states as the github repository https://github.com/MorsGames/sm64-port.git  but for compiling the actual SM64Plus you must use https://github.com/MorsGames/sm64plus.git

Thanks a lot.

**Comment by MorsGames** [comment]
I believe that wouldn't cause a big issue since GitHub would redirect that old URL to the new one... at least I think so? I'm not sure, fixed it regardless though, thank you!
