### ISSUE TITLE
All Textures showing as Purple and Black

### ISSUE THREAD

**Issue by cgaldieri** [MorsGames/sm64plus#22]
I am having trouble trying to play the port, just see this:
![sm64plus-bug](https://user-images.githubusercontent.com/31977295/115617550-e4750d00-a2c7-11eb-942b-e3602054340c.png)
![sm64plus-bug2](https://user-images.githubusercontent.com/31977295/115617554-e5a63a00-a2c7-11eb-8505-e0f52d44b7cc.png)
![sm64plus-bug3](https://user-images.githubusercontent.com/31977295/115617557-e63ed080-a2c7-11eb-8d66-319471102992.png)
![sm64plus-bug4](https://user-images.githubusercontent.com/31977295/115617560-e6d76700-a2c7-11eb-8bc9-6a1581cf5f6d.png)
I don't know why this happens, the textures are still in the folders, i tried to use the FAQ but don't worked, i viewed the log, nothing about textures missing, im using linux mint 20.1, anyone can help?

**Comment by MorsGames** [comment]
Once again, the FAQ addresses this issue and offers a workaround. It will be fixed in the next version.

Maybe I shouldn't have closed the other issue until the issue was actually fixed so I'll leave this one open.

**Comment by cgaldieri** [comment]
did you read the bottom part?

**Comment by cgaldieri** [comment]
Because i already tried the FAQ, but here's the problems:

It's a windows directory, not a linux directory (because i use linux mint 20.1)
And even when i try to delete the gfx folder, still doesn't work.

I think it is my computer.

**Comment by MorsGames** [comment]
Oh sorry, I didn't see the Linux Mint part.

Are you on the dev branch? Either way, I'll look into it more later today.

**Comment by cgaldieri** [comment]
yes, i am

**Comment by MorsGames** [comment]
Try the latest commit and see if that works.

**Comment by sgiraudot** [comment]
Hi, I'm using Linux Mint too, I have the same problem, I've tried with the latest commits of the `dev` branch and it did not fix it.

**Comment by ioncorimenia** [comment]
My printf was literally including the text `\x00` instead of an actual NUL. This fixed it for me.

```
diff --git a/Makefile b/Makefile
index f053527..f1255b7 100644
--- a/Makefile
+++ b/Makefile
@@ -602,11 +602,11 @@ $(BUILD_DIR)/%.ci4: %.ci4.png
 else
 
 $(BUILD_DIR)/%: %.png
-	printf "%s%b" "$(patsubst %.png,%,$^)" '\x00' > $@
+	printf "%s%b" "$(patsubst %.png,%,$^)" > $@
 
 $(BUILD_DIR)/%.inc.c: $(BUILD_DIR)/% %.png
 	hexdump -v -e '1/1 "0x%X,"' $< > $@
-	echo >> $@
+	printf '0x00\n' >> $@
 
 endif
```

**Comment by cgaldieri** [comment]
so... what i need to do, i need to change the part of the line:
`-	printf "%s%b" "$(patsubst %.png,%,$^)" '\x00' > $@`
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀^⠀⠀⠀⠀⠀
from `\x00` to `\NUL`?

**Comment by MorsGames** [comment]
> My printf was literally including the text `\x00` instead of an actual NUL. This fixed it for me.
> 
> ```
> diff --git a/Makefile b/Makefile
> index f053527..f1255b7 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -602,11 +602,11 @@ $(BUILD_DIR)/%.ci4: %.ci4.png
>  else
>  
>  $(BUILD_DIR)/%: %.png
> -	printf "%s%b" "$(patsubst %.png,%,$^)" '\x00' > $@
> +	printf "%s%b" "$(patsubst %.png,%,$^)" > $@
>  
>  $(BUILD_DIR)/%.inc.c: $(BUILD_DIR)/% %.png
>  	hexdump -v -e '1/1 "0x%X,"' $< > $@
> -	echo >> $@
> +	printf '0x00\n' >> $@
>  
>  endif
> ```

You can send a pull request and I will check when I get the time. Weirdly it works just fine on Manjaro so I didn't think that there would be issues on other distros.

**Comment by cgaldieri** [comment]
I am to send a pull request, ok?

**Comment by cgaldieri** [comment]
The pull request: https://github.com/MorsGames/sm64plus/pull/23

**Comment by cgaldieri** [comment]
This should work! Thanks for all

**Comment by cgaldieri** [comment]
MORS, the @ioncorimenia maked a pull request, so this issue is closed

**Comment by Imlonggone** [comment]
I also have the same error as well.
I deleted the GFX file, and it kept the same error.
<img width="1914" height="1197" alt="Image" src="https://github.com/user-attachments/assets/697256e4-cd5c-45e0-9fd7-dab58e1f5f4d" />
<img width="1919" height="1197" alt="Image" src="https://github.com/user-attachments/assets/99bd7712-0249-4890-818e-794956f141f6" />
<img width="1918" height="1199" alt="Image" src="https://github.com/user-attachments/assets/106977ff-de6c-4a4e-95a2-51fb48140553" />
<img width="1906" height="1196" alt="Image" src="https://github.com/user-attachments/assets/8d578a68-cfa9-45cd-98ae-acdd4bf3af7f" />
<img width="1915" height="1199" alt="Image" src="https://github.com/user-attachments/assets/ebfef328-9ab9-46d2-9e29-f7906b0bd8c3" />

**Comment by Imlonggone** [comment]
Nevermind. 
I just need to use the pull, clean, rebuild option and it fixed all the issues I had.

<img width="1919" height="1199" alt="Image" src="https://github.com/user-attachments/assets/5bb97a80-d92f-499a-bdd8-fb4fd35c8fab" />
<img width="1915" height="1197" alt="Image" src="https://github.com/user-attachments/assets/19eee7a3-aaba-476f-917d-3ff8e5ab2b4c" />
