### ISSUE TITLE
Underwater shell in instantly disappears the moment I grab it.

### ISSUE THREAD

**Issue by Zaphero1** [MorsGames/sm64plus#27]
Perhaps this is a user error problem, I've never known about how to use these shells before, but no matter what angle I approach the shell from, no matter if I tap grab or hold it, and no matter if I am holding swimming once I grab the shell or not, the shell disintegrates within moments of exiting the grab animation or perhaps the very first moment the animation ends. This occurs with both the shells I'm aware of (Jolly Roger Bay's and Dire Dire Docks'). It doesn't seem to be affected by the "improved power ups" option either. Perhaps it's an issue with another setting or an issue with the current version (1.1.3, should be 1.1.3.2 given I rebuilt it today)?

Here's my settings for reference (turned into a txt since github doesn't seem to accept ini uploads here).
[MyCocktail.txt](https://github.com/MorsGames/sm64plus/files/6445222/MyCocktail.txt)

**Comment by MorsGames** [comment]
Sorry for the long wait, the latest update finally fixes this!

It was apparently a typo I made in the code, whoops!
