### ISSUE TITLE
Bowser's Sub not disappearing

### ISSUE THREAD

**Issue by baboiminion** [MorsGames/sm64plus#3]
In Dire, Dire Docks, I was using the option where you don't leave the level when getting a star, but whenever I re-enter the area, Bowser's Sub doesn't disappear even though I have the star for it. If there's a way to get the sub to disappear without fully resetting my save, then thanks.
![Super Mario 64 Plus v1 0 1 (Direct3D 11) 4_7_2021 4_16_43 PM](https://user-images.githubusercontent.com/82122043/113935866-abfc0c00-97bc-11eb-9f2e-629b65b27b3c.png)

**Comment by MorsGames** [comment]
This is how it works in the original game, you have to finish Bowser in the Fire Sea to have the sub disappear. If it still doesn't disappear after that I'll reopen this.
