### ISSUE TITLE
icon.res file not recognized: File format not recognized

### ISSUE THREAD

**Issue by Wtab** [MorsGames/sm64plus#31]
When i was almost done making my compiled sm64plus folder,  I ran to this error please help!

**Comment by MorsGames** [comment]
Did the error prevent you from compiling completely? Usually, it gives a warning but compiles well otherwise.

I think I messed up something while setting that up so I'll keep this issue up until I fix that.

**Comment by Wtab** [comment]
Sorry for late respond and yes it did.

**Comment by MorsGames** [comment]
Just follow what the faq is suggesting in that case until i find a fix

**Comment by Wooty-B** [comment]
I had trouble with this too, and am building for aarch64 on an LX2K workstation. I managed to compile it by editing the Makefile in the "sm64plus" project root and deleted the only reference to "icon.res". It then compiled successfully and the game runs solid.

It's possible @Wtab is running on ARM hardware as well and this may only affect ARM hosts. Thanks!

**Comment by Wtab** [comment]
Oh thanks.
