### ISSUE TITLE
[Feature Request] Disable CRC ROM check

### ISSUE THREAD

**Issue by LukasThyWalls** [MorsGames/sm64plus#32]
Hello. Thanks for the work, it looks amazing!

I was wondering if there is a way or it could be possible to make in the building phase to disable the CRC check for the ROM to use other ROMs. It could be fail, but there is fan-translation that work in the original hardware (based in the same rom that the one you use) and maybe they can work with this port too.

Or maybe you know they would fail anyway, so then nevermind.

Thanks!

**Comment by MorsGames** [comment]
The base ROM is only used to extract assets. Stuff like the game logic, text, and whatnot are all a part of the actual source code that's in this repo. So it would simply not work.
