### ISSUE TITLE
Internal Resolution Width and Height switched-up in the menu

### ISSUE THREAD

**Issue by JovanLozanac** [MorsGames/sm64plus#34]
I noticed that, in the config menu, the settings "Internal Resolution Width" and "Internal Resolution Height" have switched names (and names only, not even descriptions on the bottom of the screen), but they work as if it is not switched. For example, setting "Internal Resolution Width" to 240 and "Internal Resolution Height" to 320 the game will render a 320x240 resolution.

Also not a big issue but can I launch the config menu (where all the settings are) fullscreen? I think it only works windowed

**Comment by MorsGames** [comment]
Yeah I noticed that a bit too late, it will be fixed in 2.0 for sure.
