### ISSUE TITLE
Package libusb-1.0 was not found in the pkg-config search path

### ISSUE THREAD

**Issue by ryu-ketsueki** [MorsGames/sm64plus#37]
I'm building from Tumbleweed with all dependencies met, although the building process can't find libusb even though it is installed. Here says I can add the directory containing the required file but doesn't say where or how.

**Comment by Wooty-B** [comment]
I come from Debian but have you installed the "libusb-devel" package?

**Comment by ryu-ketsueki** [comment]
Turns out that was the problem but I forgot to say it here. But thanks anyway.
