### ISSUE TITLE
[Feature request] Input mapping rework

### ISSUE THREAD

**Issue by alessiocameroni** [MorsGames/sm64plus#38]
I recently got a PlayStation controller, and due to how the SM64P launcher manages input mapping, i can't play with that controller. In general though, the Input mapping screen could be reworked to be better and more intuitive: you want the user to map their controller to the in-game controller, which i assume is tied to the N64 Controller's logic.

Here's a quick concept i've thrown so you can get the idea.
![Slide 16_9 - 1](https://user-images.githubusercontent.com/81615316/129750233-4b3ceafc-7160-4a20-862b-4452430a2cd4.png)

I was wondering if it would be possible to make the user select the device they want to use and then bind the chosen button accordingly.

**Comment by MorsGames** [comment]
This isn't a launcher problem, but rather a game problem, there's simply no support for anything other than XInput controllers, which are mostly just Xbox and Xbox-styled ones.

I know that even still the mapping interface isn't the most intuitive, but I do have plans to have a fancier interface for that in the future, it's just not a high priority thing for me right now.

That being said, this isn't an issue anymore. The next version (2.0) will be coming out in a few days, and most controllers should work just fine there, including DualSense. Until then you can use something like DS4Windows I suppose.
