### ISSUE TITLE
How do I access settings menu?

### ISSUE THREAD

**Issue by Wooty-B** [MorsGames/sm64plus#41]
Following "sm64-port" guides, when pausing the game and pressing "Right Shift", an options menu should load in order to change basic settings. I followed the FAQ here and the closest thing I found was: "Hold down backspace or select on the "Press Any Key" screen until the screen goes white". I do not see a "Press Any Key" screen unless you are referencing "Press Start" screen, however pressing "Backspace" here or while paused does nothing.

Please let me know if I'm missing anything, I compiled this from your sources. Thanks.

**Comment by MorsGames** [comment]
The launcher is a separate tool and there is no in-game options menu yet. I believe that the in-game options menu is a part of sm64ex, and this fork is based on sm64-port.

You can get it from below:
https://www.mfgg.net/?act=resdb&param=02&c=2&id=38190
