### ISSUE TITLE
"Stay In Course After Getting A Star" unlocking cannons without exiting the stage

### ISSUE THREAD

**Issue by HerrahStrings** [MorsGames/sm64plus#45]
When staying in the course after completing Big Bob-omb on the summit, you have to manually exit the course in order to get the new bob-omb buddy dialogue that unlocks the usage of cannons.

I can imagine this being either really simple or really complicated to change, but I figured i'd post it anyway!

**Comment by MorsGames** [comment]
If you set the "Stay In Course After Getting A Star" setting to "Auto" and "Auto Switch to the Next Mission" setting to "On" then you should get pretty much get exactly what you're asking for. Previously there were some issues with the former setting but with this latest update those should be fixed too.
