### ISSUE TITLE
[ISSUE] Mario's hat at the start of the game becomes black and his mustache does too, when you play the game it turns fully black.

### ISSUE THREAD

**Issue by zachisacooldude** [MorsGames/sm64plus#47]
I've tried using different Z64 files, but it hasn't been working at all, does anyone know a fix for this? I also reinstalled the game.

![bug](https://user-images.githubusercontent.com/90732661/137600125-2a578d4e-df30-41ee-be38-a51fee3c48aa.png)

**Comment by 24Hz** [comment]
Just fixed this myself, something must be resetting or corrupting the "Color" options in  the launcher. If you go to that section in options you'll see all our colors were set to #000000 for some reason, Quickest fix is going to the far left "Presets" menu wthin options and loading Recommended.ini then modifying settings to suit yourself from there.

**Comment by zachisacooldude** [comment]
Thanks, closing now.

**Comment by zachisacooldude** [comment]
Thanks, closing now.
