### ISSUE TITLE
Crash Related to "Stay in Course After Getting a Star: Ask" Option

### ISSUE THREAD

**Issue by atillaturkmen** [MorsGames/sm64plus#48]
The game shuts down abruptly after the red coin star is collected in the first bowser boss level if "stay at level" option is selected.

**Comment by MorsGames** [comment]
I couldn't replicate the crash myself.

That being said, I just fixed some other issues related to that exact setting so _I don't think_ that it will happen anymore. Still, let me know if the issue persists and I will reopen this if it does.

**Comment by nateify** [comment]
Hello, I am able to reproduce this bug on 4.0.0.  I attached a zip of my save bin and settings ini files. I enabled moon jump and god mode to make reproducing the issue easier, but the crash happens with those disabled. I have a crash dump file  but it is too large to upload here.

[SM64Plus.zip](https://github.com/user-attachments/files/26163642/SM64Plus.zip)
