### ISSUE TITLE
"Unused Pyramid Cutscene" doesn't return camera to player while riding shell

### ISSUE THREAD

**Issue by samvk** [MorsGames/sm64plus#49]
"Unused Pyramid Cutscene" doesn't return camera to player while riding shell. Instead the camera will freeze in place, the pyramid will explode in the background, and the camera will remain frozen indefinitely until Mario (whom you can still control albeit you probably can't see him) falls off the shell - at which point the camera will zoom in to the (already exploded) pyramid top, and finally return to the player. 
Semi-common occurance as it's the easiest way to get atop all the pillars.

Tested with both Lakitu cam and Mario cam.

Video: 

https://user-images.githubusercontent.com/12996081/142932403-c7e71d72-ed9d-42cf-b226-f129d4cecacd.mp4

(Not sure if any of this is actually directly related to this project.)

**Comment by MorsGames** [comment]
Thanks for reporting this, should be fixed in the latest update!
