### ISSUE TITLE
Using mouse left/right buttons DirectInput codes don't seems to work

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [MorsGames/sm64plus#5]
has the title says trying to use any mouse pointer DirectInput codes has bindable keys through editing the the ini, makes the game to don't read them even though they are valid here's how my key mapping looks:

```
[KEY MAPPING]
key_a = "257"
key_b = "256"
key_start = "28"
key_l = "46"
key_r = "54"
key_z = "37"
key_cup = "328"
key_cdown = "336"
key_cleft = "331"
key_cright = "333"
key_stickup = "17"
key_stickdown = "31"
key_stickleft = "30"
key_stickright = "32"
```
Key codes **256** and **257** are valid according to the DirectInput code table, but the game seems to be ignoring them.

EDIT: I forgot to tell that i was trying to mimic sm64ex key layout

**Comment by MorsGames** [comment]
There's no support for anything mouse related yet. The next version will have a separate menu dedicated to it with a bunch of features. The dev branch actually already contains those changes, but there's no launcher for it yet.
