### ISSUE TITLE
Wrong course name

### ISSUE THREAD

**Issue by Sayo-Exo** [MorsGames/sm64plus#6]
I paused the game and the course name was wrong; I had collected all stars in Shifting Sand Land except for 100 coins and haven't visited Dire Dire Docks yet, I have the automatically choose the next star available option enabled, so maybe it has something to do with 100 coins?
![image](https://user-images.githubusercontent.com/75951527/114281994-7864f000-9a0f-11eb-9e36-1ccf67417e7b.png)

**Comment by MorsGames** [comment]
I think it's just the game switching to the next available star after you collected the last one. Since the 100 coin star doesn't have an actual name it just jumps to another course. I'll take a look at it.

**Comment by MorsGames** [comment]
Should be fixed now in the dev branch.
