### ISSUE TITLE
Missing textures (Linux Latest Build)

### ISSUE THREAD

**Issue by bladehorton** [MorsGames/sm64plus#68]
Certain HUD elements are missing such as the "Peach" text on Peach's letter, Mario's face on the lives counter and the coin icon on the coin counter. I have compiled it twice and both times it still happens. The ROM is fine

**Comment by brycesweaver** [comment]
I've built and ran this on an Ubuntu machine and had no problems but when moving the install to my steam deck (arch) I experience these issues.

**Comment by NuVanDibe** [comment]
building within ubuntu on steam deck via distrobox and then running from arch creates this same issue.

**Comment by eskoONE** [comment]
> > This resolved the issue for me: https://github.com/MorsGames/sm64plus/wiki/Frequently-Asked-Questions#q-some-of-the-textures-appear-black-and-purple-how-do-i-fix-this
> > Specifcially:
> > > On non-Windows platforms, you can also try passing the path to the gfx directory as the first argument to the executable; by default, it's generated at sm64plus/build/us_pc/gfx.
> 
> Thank you, this fixed the issue for me.

how did you do that? im also having the same issue on the steam deck but im not sure how or where to pass the directory to the executable.

**Comment by brycesweaver** [comment]
> 

Add the game to steam as a non-steam game, go to game properties and in **LAUNCH OPTIONS** just put **gfx** that should fix it.

**Comment by eskoONE** [comment]
> > 
> 
> Add the game to steam as a non-steam game, go to game properties and in **LAUNCH OPTIONS** just put **gfx** that should fix it.

that didn't work unfortunately. perhaps because I'm using the launcher for it? can I make it work with that?

**Comment by bladehorton** [comment]
I have finally solved the issue. It looks as if the game isn't correctly loading in the textures from the gfx folder in the build directory. So, it would make sense that using the gfx folder in the root of sm64plus would work, except it doesn't. There aren't the right textures there at all. At least, not in my case. If you tried the "gfx" launch option in Steam and it diidn't work, instead put in the entire directory to the gfx folder THAT IS IN THE BUILD DIRECTORY, NOT THE SM64 PLUS FOLDER.

Example: "/home/blade/Games/Super Mario 64 Plus/bin/sm64plus/build/us_pc/gfx/"
As you can see, it is now pointing to the build gfx folder, as the "gfx" launch command was pointing to the gfx folder contained in "sm64plus".
