### ISSUE TITLE
Incorrect amount of total stars shown in Big Boo's Haunt

### ISSUE THREAD

**Issue by Engiturtle01** [MorsGames/sm64plus#7]
When "Show the Collected Stars" is enabled in the HUD options, it says Big Boo's Haunt has 7 total stars, when it only has 6.
![20210411022241_1](https://user-images.githubusercontent.com/82305122/114294518-43878600-9a6d-11eb-953a-9d2ef35ab95b.jpg)

**Comment by Engiturtle01** [comment]
Wait, nevermind. I'm dumb. That's just the hundred-coin star.

**Comment by MorsGames** [comment]
LOL it happens.
