### ISSUE TITLE
Camera gets stuck

### ISSUE THREAD

**Issue by ianstalk** [MorsGames/sm64plus#8]
On the level Bowser's Fire Sea, if you position the camera so it's under the platform at the top of the first elevator, it will get stuck under the platform. Positioning the camera where it would normally be on base Mario 64 avoids the problem.

**Comment by ianstalk** [comment]
I should note that I'm using the manual lakitu camera mode. If you can tell me where to find the config file, I'd be happy to attach it.

**Comment by MorsGames** [comment]
No need, just fixed the issue on the dev branch. Thanks for reporting the issue. 👍🏻
